### ISSUE TITLE
Fonts In Use description

### ISSUE THREAD

**Issue by nicksherman** [skullface/design-resources#3]
Thank you for including [Fonts In Use](https://fontsinuse.com) on the list! However, your description of “identifying type in print in real life” is not really accurate – the site catalogs usage across _all_ formats and media. For example: between the [web](https://fontsinuse.com/in/2/formats/3/web), [mobile](https://fontsinuse.com/in/2/formats/16/mobile), [tablet](https://fontsinuse.com/in/2/formats/14/tablet-ipad), and [film](https://fontsinuse.com/in/2/formats/15/film-video) entries, there are more than 1,500 examples of screen-based typography.

**Comment by skullface** [comment]
Hi @nicksherman! I’ve updated the description [here](https://github.com/skullface/design-resources/commit/cb1f332d2f6ca5639679524714a515d100cd946e) largely using Fonts In Use’s own language — the old description definitely didn’t do your work justice. Thank you! 💞
